name: CI Workflow

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'profile'
        required: true
        type: choice
        options:
          - orderCompleted
          - orderUnsuccessful
          - pastOrders

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.7.3'

    - name: Install dependencies
      run: npm install

    - name: Start Appium Server
      run: |
        npm install -g appium
        appium
        
    - name: Upload APK to BrowserStack
      run: |
          curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
            -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
            -F "file=@./path/to/your/app-debug.apk" \
            -o response.json

    - name: Parse App URL
      id: app_url
      run: |
          echo "::set-output name=url::$(jq -r '.app_url' response.json)"

    - name: Run Android tests on BrowserStack
      env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          APP_URL: ${{ steps.app_url.outputs.url }}

    - name: Run tests
      run: npm run ${{ inputs.profile }}
